---
target:
  repository: test
  host: 127.0.0.1:5000
  # deleteUnmanagedTags: true
  # deleteUnmanagedImages: true
sources:
- source:
    repository: barthv/coreos-flannel-multiarch
    host: docker.io
  syncLatestSemver: true
  # latestSemverRegex: "..."
  # tags:
  # - 1.0.0
  regexTags:
  - "v.+"
  # tags:
  # - 1.1.0
  # - 1.2.0
- source:
    repository: barthv/uhubctl
    host: docker.io
  # syncLatestSemver: true
  # latestSemverRegex: "..."
  tags:
  - 2.2.0
  # regexTags:
  # - ".+"
  # tags:
  # - 1.1.0
  # - 1.2.0
- source:
    repository: barthv/bitnami-fluentd-amqp
    host: docker.io
  # syncLatestSemver: true
  # latestSemverRegex: "..."
  tags:
  - 1.11.2-debian-10-r8
  # regexTags:
  # - "v*"
  # tags:
  # - 1.1.0
  # - 1.2.0
  