---
# listTimeout: 20s
# syncTagTimeout: 240s
# continueOnSyncError: true
# deleteUnmanagedTags: true
# deleteUnmanagedRepos: true
target:
  # repository: test
  host: 127.0.0.1:5000
sources:
- source:
    repository: barthv/coreos-flannel-multiarch
    host: docker.io
  # latestSemverSync: false
  # latestSemverRegex: "..."
  # omitPreReleaseTags: false
  # omitDashedTags: false
  # tags:
  # - 1.0.0
  regexTags:
  - "^v.+"
  # tags:
  # - 1.1.0
  # - 1.2.0
- source:
    repository: barthv/uhubctl
  omitPreReleaseTags: true
  tags:
  - 2.2.0
  - 2.2.0-arm64
  - 2.2.1rc1
- source:
    repository: nginx
  latestSemverSync: true
  omitPreReleasesTags: true
  omitDashedTags: true
  mutableTags:
  - latest
